// This file is auto-generated by @hey-api/openapi-ts

import type { ScapiAppEndpointsWebhookApiGetWebhookSubscriptionsResponse, ScapiAppEndpointsWebhookApiPostWebhookSubscriptionResponse, ScapiAppEndpointsWebhookApiGetWebhookSubscriptionResponse, ScapiAppEndpointsWebhookApiUpdateWebhookSubscriptionPatchResponse, ScapiAppEndpointsOrderApiGetOrdersResponse } from './types.gen';

const webhookSubscriptionSchemaSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    return data;
};

export const scapiAppEndpointsWebhookApiGetWebhookSubscriptionsResponseTransformer = async (data: any): Promise<ScapiAppEndpointsWebhookApiGetWebhookSubscriptionsResponse> => {
    data = data.map((item: any) => {
        return webhookSubscriptionSchemaSchemaResponseTransformer(item);
    });
    return data;
};

const secretWebhookSubscriptionSchemaSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    return data;
};

export const scapiAppEndpointsWebhookApiPostWebhookSubscriptionResponseTransformer = async (data: any): Promise<ScapiAppEndpointsWebhookApiPostWebhookSubscriptionResponse> => {
    data = secretWebhookSubscriptionSchemaSchemaResponseTransformer(data);
    return data;
};

export const scapiAppEndpointsWebhookApiGetWebhookSubscriptionResponseTransformer = async (data: any): Promise<ScapiAppEndpointsWebhookApiGetWebhookSubscriptionResponse> => {
    data = webhookSubscriptionSchemaSchemaResponseTransformer(data);
    return data;
};

export const scapiAppEndpointsWebhookApiUpdateWebhookSubscriptionPatchResponseTransformer = async (data: any): Promise<ScapiAppEndpointsWebhookApiUpdateWebhookSubscriptionPatchResponse> => {
    data = webhookSubscriptionSchemaSchemaResponseTransformer(data);
    return data;
};

const getOrderSchemaSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    data.updated_at = new Date(data.updated_at);
    return data;
};

const pagedGetOrderSchemaSchemaResponseTransformer = (data: any) => {
    data.items = data.items.map((item: any) => {
        return getOrderSchemaSchemaResponseTransformer(item);
    });
    return data;
};

export const scapiAppEndpointsOrderApiGetOrdersResponseTransformer = async (data: any): Promise<ScapiAppEndpointsOrderApiGetOrdersResponse> => {
    data = pagedGetOrderSchemaSchemaResponseTransformer(data);
    return data;
};