// This file is auto-generated by @hey-api/openapi-ts

/**
 * WebhookEventSchema
 */
export type WebhookEventSchema = {
    /**
     * Description
     */
    description: string;
    /**
     * Event
     */
    event: string;
};

/**
 * BadRequestSchema
 */
export type BadRequestSchema = {
    /**
     * Message
     * Error message
     */
    message: string;
};

/**
 * EventType
 */
export type EventType = 'order.created' | 'order.cancelled' | 'order.shipped' | 'order.returned' | 'order_items.shipped' | 'order_items.cancelled' | 'order_items.returned' | 'stock.updated' | 'product_master.status_updated';

/**
 * WebhookSubscriptionSchema
 */
export type WebhookSubscriptionSchema = {
    /**
     * Events
     */
    events: Array<EventType>;
    /**
     * Url
     */
    url: string;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Description
     * An optional description of what the webhook is used for.
     */
    description?: string | null;
    /**
     * Enabled
     * User side activation toggle
     */
    enabled?: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * SecretWebhookSubscriptionSchema
 */
export type SecretWebhookSubscriptionSchema = {
    /**
     * Events
     */
    events: Array<EventType>;
    /**
     * Url
     */
    url: string;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Description
     * An optional description of what the webhook is used for.
     */
    description?: string | null;
    /**
     * Enabled
     * User side activation toggle
     */
    enabled?: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Client Secret
     */
    client_secret: string;
};

/**
 * WebhookSubscriptionPostSchema
 */
export type WebhookSubscriptionPostSchema = {
    /**
     * Events
     */
    events: Array<EventType>;
    /**
     * Url
     */
    url: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * WebhookSubscriptionPatchSchemaPatch
 */
export type WebhookSubscriptionPatchSchemaPatch = {
    /**
     * Events
     */
    events?: Array<EventType> | null;
    /**
     * Url
     */
    url?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Enabled
     */
    enabled?: boolean | null;
};

/**
 * GetOrderSchema
 */
export type GetOrderSchema = {
    /**
     * Order items
     * List of order items
     */
    order_items: Array<OrderItemSchema>;
    /**
     * Order number
     * Order number of the order
     */
    order_number: string;
    /**
     * Delivery Document Url
     */
    delivery_document_url: string;
    status: OrdersAppModelsOrderOrderStatusChoices;
    /**
     * Customer Key
     * Reference key of the customer (MAPI: customer_key)
     */
    customer_key: string;
    /**
     * Carrier Key
     * Carrier key
     */
    carrier_key: string;
    /**
     * Shop
     */
    shop: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Fulfillment Type
     * Fulfillment type
     */
    fulfillment_type?: string;
    /**
     * Custom Data
     * Custom data (MAPI: customData)
     */
    custom_data?: {
        [key: string]: unknown;
    } | null;
    /**
     * Payment Method
     * Payment method
     */
    payment_method?: string | null;
    /**
     * Billing Street
     * Billing address
     */
    billing_street: string;
    /**
     * Billing Zip Code
     * Billing zip code
     */
    billing_zip_code: string;
    /**
     * Billing City
     * Billing city
     */
    billing_city: string;
    /**
     * Billing Country Code
     * Billing country code
     */
    billing_country_code: string;
    /**
     * Billing Recipient Gender
     * Gender of the recipient
     */
    billing_recipient_gender?: string | null;
    /**
     * Billing Recipient First Name
     * First name of the recipient
     */
    billing_recipient_first_name: string;
    /**
     * Billing Recipient Last Name
     * Last name of the recipient
     */
    billing_recipient_last_name: string;
    /**
     * Billing Additional
     * Additional billing information
     */
    billing_additional?: string | null;
    /**
     * Shipping Street
     * Shipping address
     */
    shipping_street?: string | null;
    /**
     * Shipping Zip Code
     * Shipping zip code
     */
    shipping_zip_code?: string | null;
    /**
     * Shipping City
     * Shipping city
     */
    shipping_city?: string | null;
    /**
     * Shipping Country Code
     * Shipping country
     */
    shipping_country_code?: string | null;
    /**
     * Shipping Additional
     * Additional shipping information
     */
    shipping_additional?: string | null;
    /**
     * Shipping Collection Point Key
     * Shipping collection point key
     */
    shipping_collection_point_key?: string | null;
    /**
     * Shipping Collection Point Type
     * Shipping collection point type
     */
    shipping_collection_point_type?: string | null;
    /**
     * Shipping Collection Point Customer Key
     * Shipping collection point customer key
     */
    shipping_collection_point_customer_key?: string | null;
    /**
     * Shipping Collection Point Description
     * Shipping collection point description
     */
    shipping_collection_point_description?: string | null;
    /**
     * Shipping Recipient Gender
     * Gender of the recipient
     */
    shipping_recipient_gender?: string | null;
    /**
     * Shipping Recipient First Name
     * First name of the recipient
     */
    shipping_recipient_first_name: string;
    /**
     * Shipping Recipient Last Name
     * Last name of the recipient
     */
    shipping_recipient_last_name: string;
    /**
     * Currency Code
     * Currency code
     */
    currency_code: string;
    /**
     * Cost Without Tax
     * Cost of the order without tax in the smallest currency unit (e.g. cents for Euro)
     */
    cost_without_tax: number;
    /**
     * Cost With Tax
     * Cost of the order with tax in the smallest currency unit (e.g. cents for Euro)
     */
    cost_with_tax: number;
};

/**
 * OrderCreatedWebhookSchema
 */
export type OrderCreatedWebhookSchema = {
    /**
     * Id
     * ID of the webhook message
     */
    id: number;
    /**
     * Event
     * Event type of webhook message
     */
    event: 'order.created';
    /**
     * Timestamp
     * UTC timestamp when the event was created
     */
    timestamp?: string;
    /**
     * Order payload of the triggered event
     */
    message: GetOrderSchema;
    /**
     * Subscription Id
     * ID of the subscription
     */
    subscription_id?: number | null;
};

/**
 * OrderItemSchema
 */
export type OrderItemSchema = {
    /**
     * Return Tracking Key
     */
    return_tracking_key: string | null;
    /**
     * Shipment Tracking Key
     */
    shipment_tracking_key: string | null;
    /**
     * SKU
     * SKU of the product variant
     */
    sku: string;
    status: OrdersAppModelsOrderItemOrderItemStatusChoices;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Vat
     * The tax percentage
     */
    vat?: number;
    /**
     * Price Without Tax
     * Price of the product excluding tax in the smallest currency unit (e.g. cents for Euro)
     */
    price_without_tax: number;
    /**
     * Price With Tax
     * Price of the product including tax in the smallest currency unit (e.g. cents for Euro)
     */
    price_with_tax: number;
    /**
     * Custom Data
     * Custom data for the order item
     */
    custom_data?: {
        [key: string]: unknown;
    } | null;
};

/**
 * StatusChoices
 */
export type OrdersAppModelsOrderOrderStatusChoices = 'open' | 'shipped' | 'cancelled' | 'returned' | 'mixed';

/**
 * StatusChoices
 */
export type OrdersAppModelsOrderItemOrderItemStatusChoices = 'open' | 'shipped' | 'cancelled' | 'returned';

/**
 * OrderCancelledWebhookSchema
 */
export type OrderCancelledWebhookSchema = {
    /**
     * Id
     * ID of the webhook message
     */
    id: number;
    /**
     * Event
     * Event type of webhook message
     */
    event: 'order.cancelled';
    /**
     * Timestamp
     * UTC timestamp when the event was created
     */
    timestamp?: string;
    /**
     * Order payload of the triggered event
     */
    message: GetOrderSchema;
    /**
     * Subscription Id
     * ID of the subscription
     */
    subscription_id?: number | null;
};

/**
 * OrderShippedWebhookSchema
 */
export type OrderShippedWebhookSchema = {
    /**
     * Id
     * ID of the webhook message
     */
    id: number;
    /**
     * Event
     * Event type of webhook message
     */
    event: 'order.shipped';
    /**
     * Timestamp
     * UTC timestamp when the event was created
     */
    timestamp?: string;
    /**
     * Order payload of the triggered event
     */
    message: GetOrderSchema;
    /**
     * Subscription Id
     * ID of the subscription
     */
    subscription_id?: number | null;
};

/**
 * OrderReturnedWebhookSchema
 */
export type OrderReturnedWebhookSchema = {
    /**
     * Id
     * ID of the webhook message
     */
    id: number;
    /**
     * Event
     * Event type of webhook message
     */
    event: 'order.returned';
    /**
     * Timestamp
     * UTC timestamp when the event was created
     */
    timestamp?: string;
    /**
     * Order payload of the triggered event
     */
    message: GetOrderSchema;
    /**
     * Subscription Id
     * ID of the subscription
     */
    subscription_id?: number | null;
};

/**
 * GetShipmentSchema
 */
export type GetShipmentSchema = {
    /**
     * Shipment items
     * List of order items in this shipment
     */
    items: Array<OrderItemSchema>;
    /**
     * Carrier Key
     */
    carrier_key?: string | null;
    /**
     * Return Tracking Key
     */
    return_tracking_key?: string | null;
    /**
     * Tracking Key
     */
    tracking_key?: string | null;
};

/**
 * ShipmentItemsShippedWebhookSchema
 */
export type ShipmentItemsShippedWebhookSchema = {
    /**
     * Id
     * ID of the webhook message
     */
    id: number;
    /**
     * Event
     * Event type of webhook message
     */
    event: 'order_items.shipped';
    /**
     * Timestamp
     * UTC timestamp when the event was created
     */
    timestamp?: string;
    /**
     * Shipment payload of the triggered event
     */
    message: GetShipmentSchema;
    /**
     * Subscription Id
     * ID of the subscription
     */
    subscription_id?: number | null;
};

/**
 * StatusChoices
 */
export type StatusChoices = 'open' | 'shipped' | 'cancelled' | 'returned';

/**
 * ShipmentItemsCancelledWebhookSchema
 */
export type ShipmentItemsCancelledWebhookSchema = {
    /**
     * Id
     * ID of the webhook message
     */
    id: number;
    /**
     * Event
     * Event type of webhook message
     */
    event: 'order_items.cancelled';
    /**
     * Timestamp
     * UTC timestamp when the event was created
     */
    timestamp?: string;
    /**
     * Shipment payload of the triggered event
     */
    message: GetShipmentSchema;
    /**
     * Subscription Id
     * ID of the subscription
     */
    subscription_id?: number | null;
};

/**
 * ShipmentItemsReturnedWebhookSchema
 */
export type ShipmentItemsReturnedWebhookSchema = {
    /**
     * Id
     * ID of the webhook message
     */
    id: number;
    /**
     * Event
     * Event type of webhook message
     */
    event: 'order_items.returned';
    /**
     * Timestamp
     * UTC timestamp when the event was created
     */
    timestamp?: string;
    /**
     * Shipment payload of the triggered event
     */
    message: GetShipmentSchema;
    /**
     * Subscription Id
     * ID of the subscription
     */
    subscription_id?: number | null;
};

/**
 * StockWebhookMessageSchema
 */
export type StockWebhookMessageSchema = {
    /**
     * Id
     * ID of the webhook message
     */
    id: number;
    /**
     * Event
     * Event type of webhook message
     */
    event: 'stock.updated';
    /**
     * Timestamp
     * UTC timestamp when the event was created
     */
    timestamp?: string;
    /**
     * Message
     * Stock payload of the triggered event
     */
    message: Array<WebhookStockSchema>;
    /**
     * Subscription Id
     * ID of the subscription
     */
    subscription_id?: number | null;
};

/**
 * WebhookStockSchema
 */
export type WebhookStockSchema = {
    /**
     * Sku
     * Stock Keeping Unit identifier
     */
    sku: string;
    /**
     * Quantity
     * Stock quantity of the product variant in the merchant's warehouse.
     */
    quantity: number | null;
    /**
     * Quantity Fbm
     * Stock quantity of the product variant in ABOUT YOU warehouses.
     */
    quantity_fbm: number | null;
};

/**
 * GetProductMasterSchema
 */
export type GetProductMasterSchema = {
    /**
     * External Reference Key
     * Style key of the product master
     */
    external_reference_key?: string | null;
    /**
     * Status
     * Current status of the product master
     */
    status: string;
    /**
     * Rejection Reasons
     * Rejection reasons if the product master is rejected
     */
    rejection_reasons?: Array<RejectionReasonSchema> | null;
    /**
     * Rejection Message
     * Rejection message if the product master is rejected
     */
    rejection_message?: string | null;
    /**
     * Rejected Product Ids Hint
     * Hint about which products are affected by rejection
     */
    rejected_product_ids_hint?: Array<string> | null;
};

/**
 * ProductMasterStatusUpdatedWebhookMessageSchema
 */
export type ProductMasterStatusUpdatedWebhookMessageSchema = {
    /**
     * Id
     * ID of the webhook message
     */
    id: number;
    /**
     * Event
     * Event type of webhook message
     */
    event: 'product_master.status_updated';
    /**
     * Timestamp
     * UTC timestamp when the event was created
     */
    timestamp?: string;
    /**
     * Product master payload of the triggered event
     */
    message: GetProductMasterSchema;
    /**
     * Subscription Id
     * ID of the subscription
     */
    subscription_id?: number | null;
};

/**
 * RejectionReasonSchema
 */
export type RejectionReasonSchema = {
    /**
     * Key
     */
    key: string;
    /**
     * Type
     */
    type: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * GetProductsParams
 */
export type GetProductsParams = {
    /**
     * Style Key
     * Style key to search for
     */
    style_key?: string | null;
    /**
     * SKU
     * SKU to search for
     */
    sku?: string | null;
    /**
     * Status
     * Status of the product to filter by. Choose from: "draft", "pending_approval", "rejected", "pending_active", "active", "inactive", "problem".
     */
    status?: Status | null;
};

/**
 * Input
 * Schema for pagination input parameters.
 *
 * Attributes:
 * page (int): The page number to retrieve items from (default: 1, must be ≥ 1).
 * per_page (int): The number of items per page (default: 20, must be between 1 and 100).
 */
export type Input = {
    /**
     * Page
     * Page number to retrieve items from.
     */
    page?: number;
    /**
     * Per Page
     * Number of items per page.
     */
    per_page?: number;
};

/**
 * Status
 */
export type Status = 'draft' | 'pending_approval' | 'rejected' | 'pending_active' | 'active' | 'inactive' | 'problem';

/**
 * GetProductItemSchema
 */
export type GetProductItemSchema = {
    /**
     * Style Key
     */
    style_key: string | null;
    status: Status;
    /**
     * Sku
     */
    sku: string;
    /**
     * Ean
     */
    ean: string | null;
    /**
     * Name
     */
    name: string | null;
    /**
     * Description
     * Use descriptions instead
     * @deprecated
     */
    description: string | null;
    descriptions: LocalizedDescriptionSchema | null;
    /**
     * Color
     */
    color: number | null;
    /**
     * Size
     */
    size: number | null;
    /**
     * Second Size
     */
    second_size: number | null;
    /**
     * Brand
     */
    brand: number;
    /**
     * Category
     */
    category: number;
    /**
     * Quantity
     * Stock quantity of the product variant in the merchant's warehouse.
     */
    quantity: number | null;
    /**
     * Quantity Fbm
     * Stock quantity of the product variant in ABOUT YOU warehouses.
     */
    quantity_fbm: number | null;
    /**
     * Weight
     */
    weight: number | null;
    /**
     * Countries
     */
    countries: Array<string>;
    /**
     * Country Of Origin
     */
    country_of_origin: string | null;
    /**
     * Attributes
     */
    attributes: Array<number>;
    /**
     * Material Composition Textile
     */
    material_composition_textile?: Array<MaterialCompositionTextileSchema> | null;
    /**
     * Material Composition Non Textile
     */
    material_composition_non_textile?: Array<MaterialCompositionNonTextileSchema> | null;
    /**
     * Prices
     */
    prices: Array<PriceSchema>;
    /**
     * Images
     */
    images: Array<string>;
};

/**
 * GetProductsResponseSchema
 */
export type GetProductsResponseSchema = {
    /**
     * Items
     */
    items: Array<GetProductItemSchema>;
    pagination: Pagination;
};

/**
 * LocalizedDescriptionSchema
 * Schema for handling localized descriptions with locale keys.
 */
export type LocalizedDescriptionSchema = {
    [key: string]: string;
};

/**
 * MaterialCompositionNonTextileSchema
 */
export type MaterialCompositionNonTextileSchema = {
    /**
     * Cluster Id
     * ID (integer) of this property
     */
    cluster_id: number;
    /**
     * Components
     */
    components: Array<NonTextileMaterialSchema>;
};

/**
 * MaterialCompositionTextileSchema
 */
export type MaterialCompositionTextileSchema = {
    /**
     * Cluster Id
     * ID (integer) of this property
     */
    cluster_id: number;
    /**
     * Components
     */
    components: Array<TextileMaterialSchema>;
};

/**
 * NonTextileMaterialSchema
 */
export type NonTextileMaterialSchema = {
    /**
     * Material Id
     * ID (integer) of this property
     */
    material_id: number;
};

/**
 * Pagination
 */
export type Pagination = {
    /**
     * Per Page
     */
    per_page: number;
    /**
     * Page
     */
    page: number;
    /**
     * Pages
     */
    pages: number;
    /**
     * Total
     */
    total: number;
    /**
     * Next
     */
    next: string | null;
    /**
     * Prev
     */
    prev: string | null;
};

/**
 * PriceSchema
 */
export type PriceSchema = {
    /**
     * Country Code
     * ISO 3166-1 alpha-2 country code
     */
    country_code: string;
    /**
     * Retail Price
     */
    retail_price: number;
    /**
     * Sale Price
     */
    sale_price?: number | null;
};

/**
 * TextileMaterialSchema
 */
export type TextileMaterialSchema = {
    /**
     * Material Id
     * ID (integer) of this property
     */
    material_id: number;
    /**
     * Fraction
     * Fraction of the material in the composition in percentage.
     */
    fraction: number;
};

/**
 * BatchRequestResponseSchema
 */
export type BatchRequestResponseSchema = {
    /**
     * Batchrequestid
     * Unique identifier (UUID)
     */
    batchRequestId: string;
};

/**
 * UpsertProductItemSchema
 */
export type UpsertProductItemSchema = {
    /**
     * Style Key
     * Unique style key for the product.
     */
    style_key: string;
    /**
     * Sku
     */
    sku: string;
    /**
     * Ean
     */
    ean?: string | null;
    /**
     * Hs Code
     */
    hs_code?: string | null;
    /**
     * Name
     * Include only the product/design name. Don't add categories, colors, materials etc. If there is no specific design name, leave the field empty.
     */
    name?: string | null;
    /**
     * Description
     * Use descriptions instead
     * @deprecated
     */
    description?: string | null;
    descriptions?: LocalizedDescriptionSchema | null;
    /**
     * Color
     * ID (integer) of this property
     */
    color: number;
    /**
     * Size
     */
    size: number | null;
    /**
     * Second Size
     */
    second_size?: number | null;
    /**
     * Brand
     * ID (integer) of this property
     */
    brand: number;
    /**
     * Category
     * ID (integer) of this property
     */
    category: number;
    /**
     * Quantity
     * Quantity of the product variant.
     */
    quantity?: number | null;
    /**
     * Weight
     * Weight of the product in grams.
     */
    weight: number;
    /**
     * Countries
     */
    countries: Array<string>;
    /**
     * Country Of Origin
     * ISO 3166-1 alpha-2 country code
     */
    country_of_origin: string;
    /**
     * Attributes
     */
    attributes: Array<number>;
    /**
     * Material Composition Textile
     */
    material_composition_textile?: Array<MaterialCompositionTextileSchema> | null;
    /**
     * Material Composition Non Textile
     */
    material_composition_non_textile?: Array<MaterialCompositionNonTextileSchema> | null;
    /**
     * Prices
     */
    prices: Array<PriceSchema>;
    /**
     * Images
     */
    images: Array<string>;
};

/**
 * UpsertProductSchema
 */
export type UpsertProductSchema = {
    /**
     * Items
     * List of product variants to upsert.
     */
    items: Array<UpsertProductItemSchema>;
};

/**
 * RejectedProductsParams
 */
export type RejectedProductsParams = {
    /**
     * Style Key
     * Style key to search for
     */
    style_key?: string | null;
};

/**
 * PagedRejectedProductSchema
 */
export type PagedRejectedProductSchema = {
    /**
     * Items
     */
    items: Array<RejectedProductSchema>;
    pagination: Pagination;
};

/**
 * RejectedProductSchema
 */
export type RejectedProductSchema = {
    /**
     * Style Key
     * Style key of the product
     */
    style_key?: string | null;
    /**
     * Rejection Reasons
     */
    rejection_reasons: Array<RejectionReasonSchema>;
    /**
     * Rejection Message
     * The rejection message for the product master
     */
    rejection_message?: string | null;
    /**
     * Rejected Product Ids Hint
     * Used to hint which products are affected by the rejection reason given
     */
    rejected_product_ids_hint?: {
        [key: string]: unknown;
    } | null;
};

/**
 * UpdateProductStatusResponseSchema
 */
export type UpdateProductStatusResponseSchema = {
    /**
     * Batchrequestid
     * Unique identifier (UUID)
     */
    batchRequestId: string;
};

/**
 * ProductStatusChoices
 */
export type ProductStatusChoices = 'published' | 'inactive' | 'draft';

/**
 * UpdateProductStatusItemSchema
 */
export type UpdateProductStatusItemSchema = {
    /**
     * Style Key
     * Style key for the group of products
     */
    style_key: string;
    /**
     * Status you want to set for the given product
     */
    status: ProductStatusChoices;
};

/**
 * UpdateProductStatusSchema
 */
export type UpdateProductStatusSchema = {
    /**
     * Items
     * List of style_keys and corresponding status to update.
     */
    items: Array<UpdateProductStatusItemSchema>;
};

/**
 * UpdateStockResponseSchema
 */
export type UpdateStockResponseSchema = {
    /**
     * Batchrequestid
     * Unique identifier (UUID)
     */
    batchRequestId: string;
};

/**
 * UpdateStockItemSchema
 */
export type UpdateStockItemSchema = {
    /**
     * Sku
     * Stock Keeping Unit identifier
     */
    sku: string;
    /**
     * Quantity
     * Quantity to update
     */
    quantity: number;
};

/**
 * UpdateStockSchema
 */
export type UpdateStockSchema = {
    /**
     * Items
     * List of stock items to update
     */
    items: Array<UpdateStockItemSchema>;
};

/**
 * UpdatePriceResponseSchema
 */
export type UpdatePriceResponseSchema = {
    /**
     * Batchrequestid
     * Unique identifier (UUID)
     */
    batchRequestId: string;
};

/**
 * UpdatePriceItemSchema
 */
export type UpdatePriceItemSchema = {
    /**
     * Sku
     * Stock Keeping Unit identifier
     */
    sku: string;
    price: PriceSchema;
};

/**
 * UpdatePriceSchema
 */
export type UpdatePriceSchema = {
    /**
     * Items
     * List of price items to update
     */
    items: Array<UpdatePriceItemSchema>;
};

/**
 * ListCategoriesParams
 */
export type ListCategoriesParams = {
    /**
     * Query
     * Search term to filter items by path name
     */
    query?: string | null;
    /**
     * Parent Category
     * Filter items by parent category ID
     */
    parent_category?: number | null;
};

/**
 * CategorySchema
 */
export type CategorySchema = {
    /**
     * Id
     * ID (integer) of this property
     */
    id: number;
    /**
     * Name
     * Name of the category
     */
    name: string;
    /**
     * Path
     * Path of the category for display purposes
     */
    path: string;
    /**
     * Parent Id
     * ID of the parent category or null if it's a root category
     */
    parent_id?: number | null;
    /**
     * Material Composition Type
     * Material composition type based on mandatory attribute groups
     */
    material_composition_type?: ('textile' | 'non-textile') | null;
    /**
     * Parent
     */
    parent?: number | null;
};

/**
 * GetCategoriesResponseSchema
 */
export type GetCategoriesResponseSchema = {
    /**
     * Items
     */
    items: Array<CategorySchema>;
    pagination: Pagination;
};

/**
 * AttributeGroupSchema
 */
export type AttributeGroupSchema = {
    /**
     * Attributes
     */
    attributes: Array<AttributeSchema>;
    /**
     * Id
     * ID (integer) of this property
     */
    id: number;
    /**
     * Name
     * Name of the attribute group
     */
    name: string;
    /**
     * Frontend Name
     * Name of the attribute group for display purposes
     */
    frontend_name: string;
    /**
     * Is Multiselect
     * Whether the group allows multiple attributes to be selected
     */
    is_multiselect?: boolean | null;
};

/**
 * AttributeSchema
 */
export type AttributeSchema = {
    /**
     * Id
     * ID (integer) of this property
     */
    id: number;
    /**
     * Name
     * Name of the attribute
     */
    name: string;
    /**
     * Frontend Name
     * Name of the attribute for display purposes
     */
    frontend_name: string;
};

/**
 * CountriesAndLocalesResponseSchema
 */
export type CountriesAndLocalesResponseSchema = {
    /**
     * Countries
     */
    countries: Array<CountrySchema>;
    /**
     * Locales
     */
    locales: Array<LocaleSchema>;
    /**
     * Currencies
     */
    currencies: Array<CurrencySchema>;
};

/**
 * CountrySchema
 */
export type CountrySchema = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
};

/**
 * CurrencySchema
 */
export type CurrencySchema = {
    /**
     * Country Code
     */
    country_code: string;
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
};

/**
 * LocaleSchema
 */
export type LocaleSchema = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
};

/**
 * BrandSchema
 */
export type BrandSchema = {
    /**
     * Id
     * ID (integer) of this property
     */
    id: number;
    /**
     * Key
     * Identifier of the brand
     */
    key: string;
    /**
     * Name
     * Name of the brand
     */
    name: string;
};

/**
 * RequestStatus
 */
export type RequestStatus = 'pending' | 'processing' | 'completed' | 'failed';

/**
 * UpsertProductBatchResultsResponseSchema
 */
export type UpsertProductBatchResultsResponseSchema = {
    /**
     * Batchrequestid
     * Unique identifier (UUID)
     */
    batchRequestId: string;
    /**
     * Status of the batch processing
     */
    status: RequestStatus;
    /**
     * Items
     */
    items: Array<UpsertProductResultItemSchema>;
};

/**
 * UpsertProductResultItemSchema
 */
export type UpsertProductResultItemSchema = {
    requestItem: UpsertProductItemSchema;
    /**
     * Success
     */
    success: boolean;
    /**
     * Errors
     */
    errors: Array<string>;
};

/**
 * UpdateProductStatusBatchResultsResponseSchema
 */
export type UpdateProductStatusBatchResultsResponseSchema = {
    /**
     * Batchrequestid
     * Unique identifier (UUID)
     */
    batchRequestId: string;
    /**
     * Status
     */
    status: RequestStatus | string;
    /**
     * Items
     */
    items: Array<UpdateProductStatusResultItemSchema>;
};

/**
 * UpdateProductStatusResultItemSchema
 */
export type UpdateProductStatusResultItemSchema = {
    requestItem: UpdateProductStatusItemSchema;
    /**
     * Success
     */
    success: boolean;
    /**
     * Errors
     */
    errors: Array<string>;
};

/**
 * StockBatchResultsResponseSchema
 */
export type StockBatchResultsResponseSchema = {
    /**
     * Batchrequestid
     * Unique identifier (UUID)
     */
    batchRequestId: string;
    /**
     * Status of the batch processing
     */
    status: RequestStatus;
    /**
     * Items
     * List of result items for stock update
     */
    items: Array<UpdateStockResultItemSchema>;
};

/**
 * UpdateStockResultItemSchema
 */
export type UpdateStockResultItemSchema = {
    requestItem: UpdateStockItemSchema;
    /**
     * Success
     */
    success: boolean;
    /**
     * Errors
     */
    errors: Array<string>;
};

/**
 * PriceBatchResultsResponseSchema
 */
export type PriceBatchResultsResponseSchema = {
    /**
     * Batchrequestid
     * Unique identifier (UUID)
     */
    batchRequestId: string;
    /**
     * Status of the batch processing
     */
    status: RequestStatus;
    /**
     * Items
     * List of result items for batch update
     */
    items: Array<UpdatePriceResultItemSchema>;
};

/**
 * UpdatePriceResultItemSchema
 */
export type UpdatePriceResultItemSchema = {
    requestItem: UpdatePriceItemSchema;
    /**
     * Success
     */
    success: boolean;
    /**
     * Errors
     */
    errors: Array<string>;
};

/**
 * CancelOrderItemSchema
 */
export type CancelOrderItemSchema = {
    /**
     * Id
     * Order item ID to cancel.
     */
    id: number;
};

/**
 * CancelOrderResultItemSchema
 */
export type CancelOrderResultItemSchema = {
    requestItem: CancelOrderItemSchema;
    /**
     * Success
     */
    success: boolean;
    /**
     * Errors
     */
    errors: Array<string>;
};

/**
 * CancelOrderResultsResponseSchema
 */
export type CancelOrderResultsResponseSchema = {
    /**
     * Batchrequestid
     * Unique identifier (UUID)
     */
    batchRequestId: string;
    /**
     * Status of the batch processing
     */
    status: RequestStatus;
    /**
     * Items
     * List of result items for batch cancel order
     */
    items: Array<CancelOrderResultItemSchema>;
};

/**
 * ReturnItemSchema
 */
export type ReturnItemSchema = {
    /**
     * Order Items
     * List of order item ids to return.
     */
    order_items: Array<number>;
    /**
     * Return Tracking Key
     * Return tracking key
     */
    return_tracking_key: string;
};

/**
 * ReturnResultItemSchema
 */
export type ReturnResultItemSchema = {
    requestItem: ReturnItemSchema;
    /**
     * Success
     */
    success: boolean;
    /**
     * Errors
     */
    errors: Array<string>;
};

/**
 * ReturnResultsSchema
 */
export type ReturnResultsSchema = {
    /**
     * Batchrequestid
     * Unique identifier (UUID)
     */
    batchRequestId: string;
    /**
     * Status of the batch processing
     */
    status: RequestStatus;
    /**
     * Items
     * List of result items for batch return order
     */
    items: Array<ReturnResultItemSchema>;
};

/**
 * Carrier
 */
export type Carrier = 'DHL_STD_NATIONAL' | 'HERMES_KLV' | 'HERMES_STD_NATIONAL' | 'DHL_AT' | 'DHL_POST_AUT' | 'HERMES_POST_AUT' | 'POST_CH' | 'QUICK_CH' | 'POST_NL' | 'DHL_NL' | 'DHL_PL' | 'DPD_PL' | 'UB_POST_PL' | 'PPL' | 'ZASIL_CZ' | 'BPOST_BE' | 'DHL_BPOST_BEL' | 'COLI_FR' | 'UB_GLS_DK' | 'UB_CORR_ES' | 'DS_TB_ES' | 'UB_SEUR_ES' | 'UB_CTT_PT' | 'DS_TB_PT' | 'DPD_PT' | 'ECONT_BG' | 'ACS_CY' | 'UB_OMNIVA_EE' | 'UB_POST_FI' | 'UB_TAXY_GR' | 'ACS_GR' | 'POST_HR' | 'POST_HU' | 'GLS_HU' | 'DPD_HU' | 'UB_FAST_IE' | 'POST_IT' | 'DS_TB_IT' | 'UB_OMNIVA_LT' | 'BPOST_LU' | 'UB_OMNIVA_LV' | 'UB_POST_NO' | 'FAN_RO' | 'UB_DHL_SE' | 'POST_SI' | 'POST_SK' | 'ZASIL_SK';

/**
 * ShipmentItemSchema
 */
export type ShipmentItemSchema = {
    /**
     * Order Items
     * List of order item ids to ship.
     */
    order_items: Array<number>;
    /**
     * Carrier of the shipment
     */
    carrier_key: Carrier;
    /**
     * Shipment Tracking Key
     * Tracking key of the shipment
     */
    shipment_tracking_key: string;
    /**
     * Return Tracking Key
     * Return tracking key
     */
    return_tracking_key: string;
};

/**
 * ShipmentOrderResultsResponseSchema
 */
export type ShipmentOrderResultsResponseSchema = {
    /**
     * Batchrequestid
     * Unique identifier (UUID)
     */
    batchRequestId: string;
    /**
     * Status of the batch processing
     */
    status: RequestStatus;
    /**
     * Items
     * List of result items for batch shipment order
     */
    items: Array<ShipmentResultItemSchema>;
};

/**
 * ShipmentResultItemSchema
 */
export type ShipmentResultItemSchema = {
    requestItem: ShipmentItemSchema;
    /**
     * Success
     */
    success: boolean;
    /**
     * Errors
     */
    errors: Array<string>;
};

/**
 * FulfillmentTypes
 */
export type FulfillmentTypes = 'dropshipping' | 'fulfillment_by_marketplace';

/**
 * GetOrderParams
 */
export type GetOrderParams = {
    /**
     * Order number
     * Order number to search for.
     */
    order_number?: string | null;
    /**
     * Customer key
     * Customer key to search for.
     */
    customer_key?: string | null;
    /**
     * Carrier Key
     * Carrier of the order to filter by. Choose from: "DHL_STD_NATIONAL", "HERMES_KLV", "HERMES_STD_NATIONAL", "DHL_AT", "DHL_POST_AUT", "HERMES_POST_AUT", "POST_CH", "QUICK_CH", "POST_NL", "DHL_NL", "DHL_PL", "DPD_PL", "UB_POST_PL", "PPL", "ZASIL_CZ", "BPOST_BE", "DHL_BPOST_BEL", "COLI_FR", "UB_GLS_DK", "UB_CORR_ES", "DS_TB_ES", "UB_SEUR_ES", "UB_CTT_PT", "DS_TB_PT", "DPD_PT", "ECONT_BG", "ACS_CY", "UB_OMNIVA_EE", "UB_POST_FI", "UB_TAXY_GR", "ACS_GR", "POST_HR", "POST_HU", "GLS_HU", "DPD_HU", "UB_FAST_IE", "POST_IT", "DS_TB_IT", "UB_OMNIVA_LT", "BPOST_LU", "UB_OMNIVA_LV", "UB_POST_NO", "FAN_RO", "UB_DHL_SE", "POST_SI", "POST_SK", "ZASIL_SK".
     */
    carrier_key?: Carrier | null;
    /**
     * Shop country
     * Shop country to search for.
     */
    shop_country?: string | null;
    /**
     * Status
     * Status of the order to filter by. Choose from: "open", "shipped", "cancelled", "returned", "mixed".
     */
    order_status?: OrdersAppModelsOrderOrderStatusChoices | null;
    /**
     * Status of the order item to filter by. Choose from: "open", "shipped", "cancelled", "returned".
     */
    order_item_status?: OrdersAppModelsOrderItemOrderItemStatusChoices | null;
    /**
     * Orders from
     * Orders from date to filter by.
     */
    orders_from?: string | null;
    /**
     * Orders to
     * Orders to date to filter by.
     */
    orders_to?: string | null;
    /**
     * Fulfillment type
     * Fulfillment type to filter by.
     */
    fulfillment_type?: FulfillmentTypes | null;
};

/**
 * PagedGetOrderSchema
 */
export type PagedGetOrderSchema = {
    /**
     * Items
     */
    items: Array<GetOrderSchema>;
    pagination: Pagination;
};

/**
 * CancelRequestSchema
 */
export type CancelRequestSchema = {
    /**
     * Items
     * List of order items to cancel.
     */
    items: Array<CancelOrderItemSchema>;
};

/**
 * ShipmentRequestSchema
 */
export type ShipmentRequestSchema = {
    /**
     * Items
     * List of shipments.
     */
    items: Array<ShipmentItemSchema>;
};

/**
 * ReturnRequestSchema
 */
export type ReturnRequestSchema = {
    /**
     * Items
     * List of return shipments.
     */
    items: Array<ReturnItemSchema>;
};

/**
 * ListReportsParams
 */
export type ListReportsParams = {
    /**
     * Report type
     * Filter by report type. Choose from: "SELLABLE_STOCK", "WAREHOUSE_MOVEMENTS".
     */
    type?: ReportType | null;
    /**
     * Search query
     * Search query to filter reports by ID.
     */
    query?: string | null;
};

/**
 * ReportType
 */
export type ReportType = 'SELLABLE_STOCK' | 'WAREHOUSE_MOVEMENTS';

/**
 * PagedReportSchema
 */
export type PagedReportSchema = {
    /**
     * Items
     */
    items: Array<ReportSchema>;
    pagination: Pagination;
};

/**
 * ReportSchema
 */
export type ReportSchema = {
    /**
     * Id
     * ID (integer) of this property
     */
    id: number;
    /**
     * Type of the report
     */
    type: ReportType;
    /**
     * File Name
     * Name of the report file
     */
    file_name: string;
    /**
     * File Url
     * URL to download the report file
     */
    file_url: string;
    /**
     * Date
     * Report date extracted from filename
     */
    date: string | null;
    /**
     * Created At
     * When the report was created
     */
    created_at: string;
    /**
     * Updated At
     * When the report was last updated
     */
    updated_at: string;
};

export type GetApiV1WebhooksTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/webhooks/types';
};

export type GetApiV1WebhooksTypesErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    default: unknown;
};

export type GetApiV1WebhooksTypesError = GetApiV1WebhooksTypesErrors[keyof GetApiV1WebhooksTypesErrors];

export type GetApiV1WebhooksTypesResponses = {
    /**
     * Response
     * OK
     */
    200: Array<WebhookEventSchema>;
};

export type GetApiV1WebhooksTypesResponse = GetApiV1WebhooksTypesResponses[keyof GetApiV1WebhooksTypesResponses];

export type GetApiV1WebhooksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/webhooks/';
};

export type GetApiV1WebhooksErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    default: unknown;
};

export type GetApiV1WebhooksError = GetApiV1WebhooksErrors[keyof GetApiV1WebhooksErrors];

export type GetApiV1WebhooksResponses = {
    /**
     * Response
     * OK
     */
    200: Array<WebhookSubscriptionSchema>;
};

export type GetApiV1WebhooksResponse = GetApiV1WebhooksResponses[keyof GetApiV1WebhooksResponses];

export type PostApiV1WebhooksData = {
    body: WebhookSubscriptionPostSchema;
    path?: never;
    query?: never;
    url: '/api/v1/webhooks/';
};

export type PostApiV1WebhooksErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    default: unknown;
};

export type PostApiV1WebhooksError = PostApiV1WebhooksErrors[keyof PostApiV1WebhooksErrors];

export type PostApiV1WebhooksResponses = {
    /**
     * OK
     */
    200: SecretWebhookSubscriptionSchema;
};

export type PostApiV1WebhooksResponse = PostApiV1WebhooksResponses[keyof PostApiV1WebhooksResponses];

export type DeleteApiV1WebhooksBySubscriptionIdData = {
    body?: never;
    path: {
        /**
         * Subscription Id
         */
        subscription_id: number;
    };
    query?: never;
    url: '/api/v1/webhooks/{subscription_id}';
};

export type DeleteApiV1WebhooksBySubscriptionIdErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    /**
     * Not Found
     */
    404: BadRequestSchema;
    default: unknown;
};

export type DeleteApiV1WebhooksBySubscriptionIdError = DeleteApiV1WebhooksBySubscriptionIdErrors[keyof DeleteApiV1WebhooksBySubscriptionIdErrors];

export type DeleteApiV1WebhooksBySubscriptionIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiV1WebhooksBySubscriptionIdResponse = DeleteApiV1WebhooksBySubscriptionIdResponses[keyof DeleteApiV1WebhooksBySubscriptionIdResponses];

export type GetApiV1WebhooksBySubscriptionIdData = {
    body?: never;
    path: {
        /**
         * Subscription Id
         */
        subscription_id: number;
    };
    query?: never;
    url: '/api/v1/webhooks/{subscription_id}';
};

export type GetApiV1WebhooksBySubscriptionIdErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    /**
     * Not Found
     */
    404: BadRequestSchema;
    default: unknown;
};

export type GetApiV1WebhooksBySubscriptionIdError = GetApiV1WebhooksBySubscriptionIdErrors[keyof GetApiV1WebhooksBySubscriptionIdErrors];

export type GetApiV1WebhooksBySubscriptionIdResponses = {
    /**
     * OK
     */
    200: WebhookSubscriptionSchema;
};

export type GetApiV1WebhooksBySubscriptionIdResponse = GetApiV1WebhooksBySubscriptionIdResponses[keyof GetApiV1WebhooksBySubscriptionIdResponses];

export type PatchApiV1WebhooksBySubscriptionIdData = {
    body: WebhookSubscriptionPatchSchemaPatch;
    path: {
        /**
         * Subscription Id
         */
        subscription_id: number;
    };
    query?: never;
    url: '/api/v1/webhooks/{subscription_id}';
};

export type PatchApiV1WebhooksBySubscriptionIdErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    /**
     * Not Found
     */
    404: BadRequestSchema;
    default: unknown;
};

export type PatchApiV1WebhooksBySubscriptionIdError = PatchApiV1WebhooksBySubscriptionIdErrors[keyof PatchApiV1WebhooksBySubscriptionIdErrors];

export type PatchApiV1WebhooksBySubscriptionIdResponses = {
    /**
     * OK
     */
    200: WebhookSubscriptionSchema;
};

export type PatchApiV1WebhooksBySubscriptionIdResponse = PatchApiV1WebhooksBySubscriptionIdResponses[keyof PatchApiV1WebhooksBySubscriptionIdResponses];

export type PostApiV1WebhooksOrderCreatedData = {
    body: OrderCreatedWebhookSchema;
    path?: never;
    query?: never;
    url: '/api/v1/webhooks/order-created';
};

export type PostApiV1WebhooksOrderCreatedResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1WebhooksOrderCancelledData = {
    body: OrderCancelledWebhookSchema;
    path?: never;
    query?: never;
    url: '/api/v1/webhooks/order-cancelled';
};

export type PostApiV1WebhooksOrderCancelledResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1WebhooksOrderShippedData = {
    body: OrderShippedWebhookSchema;
    path?: never;
    query?: never;
    url: '/api/v1/webhooks/order-shipped';
};

export type PostApiV1WebhooksOrderShippedResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1WebhooksOrderReturnedData = {
    body: OrderReturnedWebhookSchema;
    path?: never;
    query?: never;
    url: '/api/v1/webhooks/order-returned';
};

export type PostApiV1WebhooksOrderReturnedResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1WebhooksOrderItemsShippedData = {
    body: ShipmentItemsShippedWebhookSchema;
    path?: never;
    query?: never;
    url: '/api/v1/webhooks/order-items-shipped';
};

export type PostApiV1WebhooksOrderItemsShippedResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1WebhooksOrderItemsCancelledData = {
    body: ShipmentItemsCancelledWebhookSchema;
    path?: never;
    query?: never;
    url: '/api/v1/webhooks/order-items-cancelled';
};

export type PostApiV1WebhooksOrderItemsCancelledResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1WebhooksOrderItemsReturnedData = {
    body: ShipmentItemsReturnedWebhookSchema;
    path?: never;
    query?: never;
    url: '/api/v1/webhooks/order-items-returned';
};

export type PostApiV1WebhooksOrderItemsReturnedResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1WebhooksStockUpdatedData = {
    body: StockWebhookMessageSchema;
    path?: never;
    query?: never;
    url: '/api/v1/webhooks/stock-updated';
};

export type PostApiV1WebhooksStockUpdatedResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1WebhooksProductMasterStatusUpdatedData = {
    body: ProductMasterStatusUpdatedWebhookMessageSchema;
    path?: never;
    query?: never;
    url: '/api/v1/webhooks/product-master-status-updated';
};

export type PostApiV1WebhooksProductMasterStatusUpdatedResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Style Key
         * Style key to search for
         */
        style_key?: string | null;
        /**
         * SKU
         * SKU to search for
         */
        sku?: string | null;
        /**
         * Status
         * Status of the product to filter by. Choose from: "draft", "pending_approval", "rejected", "pending_active", "active", "inactive", "problem".
         */
        status?: Status | null;
        /**
         * Page
         * Page number to retrieve items from.
         */
        page?: number;
        /**
         * Per Page
         * Number of items per page.
         */
        per_page?: number;
    };
    url: '/api/v1/products/';
};

export type GetApiV1ProductsErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    default: unknown;
};

export type GetApiV1ProductsError = GetApiV1ProductsErrors[keyof GetApiV1ProductsErrors];

export type GetApiV1ProductsResponses = {
    /**
     * OK
     */
    200: GetProductsResponseSchema;
};

export type GetApiV1ProductsResponse = GetApiV1ProductsResponses[keyof GetApiV1ProductsResponses];

export type PostApiV1ProductsData = {
    body: UpsertProductSchema;
    path?: never;
    query?: never;
    url: '/api/v1/products/';
};

export type PostApiV1ProductsErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    default: unknown;
};

export type PostApiV1ProductsError = PostApiV1ProductsErrors[keyof PostApiV1ProductsErrors];

export type PostApiV1ProductsResponses = {
    /**
     * OK
     */
    200: BatchRequestResponseSchema;
};

export type PostApiV1ProductsResponse = PostApiV1ProductsResponses[keyof PostApiV1ProductsResponses];

export type GetApiV1ProductsRejectedData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Style Key
         * Style key to search for
         */
        style_key?: string | null;
        /**
         * Page
         * Page number to retrieve items from.
         */
        page?: number;
        /**
         * Per Page
         * Number of items per page.
         */
        per_page?: number;
    };
    url: '/api/v1/products/rejected';
};

export type GetApiV1ProductsRejectedErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    default: unknown;
};

export type GetApiV1ProductsRejectedError = GetApiV1ProductsRejectedErrors[keyof GetApiV1ProductsRejectedErrors];

export type GetApiV1ProductsRejectedResponses = {
    /**
     * OK
     */
    200: PagedRejectedProductSchema;
};

export type GetApiV1ProductsRejectedResponse = GetApiV1ProductsRejectedResponses[keyof GetApiV1ProductsRejectedResponses];

export type PutApiV1ProductsStatusData = {
    body: UpdateProductStatusSchema;
    path?: never;
    query?: never;
    url: '/api/v1/products/status';
};

export type PutApiV1ProductsStatusErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    default: unknown;
};

export type PutApiV1ProductsStatusError = PutApiV1ProductsStatusErrors[keyof PutApiV1ProductsStatusErrors];

export type PutApiV1ProductsStatusResponses = {
    /**
     * OK
     */
    200: UpdateProductStatusResponseSchema;
};

export type PutApiV1ProductsStatusResponse = PutApiV1ProductsStatusResponses[keyof PutApiV1ProductsStatusResponses];

export type PutApiV1ProductsStocksData = {
    body: UpdateStockSchema;
    path?: never;
    query?: never;
    url: '/api/v1/products/stocks';
};

export type PutApiV1ProductsStocksErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    default: unknown;
};

export type PutApiV1ProductsStocksError = PutApiV1ProductsStocksErrors[keyof PutApiV1ProductsStocksErrors];

export type PutApiV1ProductsStocksResponses = {
    /**
     * OK
     */
    200: UpdateStockResponseSchema;
};

export type PutApiV1ProductsStocksResponse = PutApiV1ProductsStocksResponses[keyof PutApiV1ProductsStocksResponses];

export type PutApiV1ProductsPricesData = {
    body: UpdatePriceSchema;
    path?: never;
    query?: never;
    url: '/api/v1/products/prices';
};

export type PutApiV1ProductsPricesErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    default: unknown;
};

export type PutApiV1ProductsPricesError = PutApiV1ProductsPricesErrors[keyof PutApiV1ProductsPricesErrors];

export type PutApiV1ProductsPricesResponses = {
    /**
     * OK
     */
    200: UpdatePriceResponseSchema;
};

export type PutApiV1ProductsPricesResponse = PutApiV1ProductsPricesResponses[keyof PutApiV1ProductsPricesResponses];

export type GetApiV1CategoriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Query
         * Search term to filter items by path name
         */
        query?: string | null;
        /**
         * Parent Category
         * Filter items by parent category ID
         */
        parent_category?: number | null;
        /**
         * Page
         * Page number to retrieve items from.
         */
        page?: number;
        /**
         * Per Page
         * Number of items per page.
         */
        per_page?: number;
    };
    url: '/api/v1/categories/';
};

export type GetApiV1CategoriesErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    default: unknown;
};

export type GetApiV1CategoriesError = GetApiV1CategoriesErrors[keyof GetApiV1CategoriesErrors];

export type GetApiV1CategoriesResponses = {
    /**
     * OK
     */
    200: GetCategoriesResponseSchema;
};

export type GetApiV1CategoriesResponse = GetApiV1CategoriesResponses[keyof GetApiV1CategoriesResponses];

export type GetApiV1CategoriesByCategoryIdAttributeGroupsData = {
    body?: never;
    path: {
        /**
         * Category Id
         */
        category_id: number;
    };
    query?: never;
    url: '/api/v1/categories/{category_id}/attribute-groups';
};

export type GetApiV1CategoriesByCategoryIdAttributeGroupsErrors = {
    default: unknown;
};

export type GetApiV1CategoriesByCategoryIdAttributeGroupsResponses = {
    /**
     * Response
     * OK
     */
    200: Array<AttributeGroupSchema>;
};

export type GetApiV1CategoriesByCategoryIdAttributeGroupsResponse = GetApiV1CategoriesByCategoryIdAttributeGroupsResponses[keyof GetApiV1CategoriesByCategoryIdAttributeGroupsResponses];

export type GetApiV1CountriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/countries/';
};

export type GetApiV1CountriesErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    default: unknown;
};

export type GetApiV1CountriesError = GetApiV1CountriesErrors[keyof GetApiV1CountriesErrors];

export type GetApiV1CountriesResponses = {
    /**
     * OK
     */
    200: CountriesAndLocalesResponseSchema;
};

export type GetApiV1CountriesResponse = GetApiV1CountriesResponses[keyof GetApiV1CountriesResponses];

export type GetApiV1BrandsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/brands/';
};

export type GetApiV1BrandsErrors = {
    default: unknown;
};

export type GetApiV1BrandsResponses = {
    /**
     * Response
     * OK
     */
    200: Array<BrandSchema>;
};

export type GetApiV1BrandsResponse = GetApiV1BrandsResponses[keyof GetApiV1BrandsResponses];

export type GetApiV1ResultsProductsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Batch Request Id
         */
        batch_request_id: string;
    };
    url: '/api/v1/results/products';
};

export type GetApiV1ResultsProductsErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    /**
     * Not Found
     */
    404: BadRequestSchema;
    default: unknown;
};

export type GetApiV1ResultsProductsError = GetApiV1ResultsProductsErrors[keyof GetApiV1ResultsProductsErrors];

export type GetApiV1ResultsProductsResponses = {
    /**
     * OK
     */
    200: UpsertProductBatchResultsResponseSchema;
};

export type GetApiV1ResultsProductsResponse = GetApiV1ResultsProductsResponses[keyof GetApiV1ResultsProductsResponses];

export type GetApiV1ResultsStatusData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Batch Request Id
         */
        batch_request_id: string;
    };
    url: '/api/v1/results/status';
};

export type GetApiV1ResultsStatusErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    /**
     * Not Found
     */
    404: BadRequestSchema;
    default: unknown;
};

export type GetApiV1ResultsStatusError = GetApiV1ResultsStatusErrors[keyof GetApiV1ResultsStatusErrors];

export type GetApiV1ResultsStatusResponses = {
    /**
     * OK
     */
    200: UpdateProductStatusBatchResultsResponseSchema;
};

export type GetApiV1ResultsStatusResponse = GetApiV1ResultsStatusResponses[keyof GetApiV1ResultsStatusResponses];

export type GetApiV1ResultsStocksData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Batch Request Id
         */
        batch_request_id: string;
    };
    url: '/api/v1/results/stocks';
};

export type GetApiV1ResultsStocksErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    /**
     * Not Found
     */
    404: BadRequestSchema;
    default: unknown;
};

export type GetApiV1ResultsStocksError = GetApiV1ResultsStocksErrors[keyof GetApiV1ResultsStocksErrors];

export type GetApiV1ResultsStocksResponses = {
    /**
     * OK
     */
    200: StockBatchResultsResponseSchema;
};

export type GetApiV1ResultsStocksResponse = GetApiV1ResultsStocksResponses[keyof GetApiV1ResultsStocksResponses];

export type GetApiV1ResultsPricesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Batch Request Id
         */
        batch_request_id: string;
    };
    url: '/api/v1/results/prices';
};

export type GetApiV1ResultsPricesErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    /**
     * Not Found
     */
    404: BadRequestSchema;
    default: unknown;
};

export type GetApiV1ResultsPricesError = GetApiV1ResultsPricesErrors[keyof GetApiV1ResultsPricesErrors];

export type GetApiV1ResultsPricesResponses = {
    /**
     * OK
     */
    200: PriceBatchResultsResponseSchema;
};

export type GetApiV1ResultsPricesResponse = GetApiV1ResultsPricesResponses[keyof GetApiV1ResultsPricesResponses];

export type GetApiV1ResultsCancelOrdersData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Batch Request Id
         */
        batch_request_id: string;
    };
    url: '/api/v1/results/cancel-orders';
};

export type GetApiV1ResultsCancelOrdersErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    /**
     * Not Found
     */
    404: BadRequestSchema;
    default: unknown;
};

export type GetApiV1ResultsCancelOrdersError = GetApiV1ResultsCancelOrdersErrors[keyof GetApiV1ResultsCancelOrdersErrors];

export type GetApiV1ResultsCancelOrdersResponses = {
    /**
     * OK
     */
    200: CancelOrderResultsResponseSchema;
};

export type GetApiV1ResultsCancelOrdersResponse = GetApiV1ResultsCancelOrdersResponses[keyof GetApiV1ResultsCancelOrdersResponses];

export type GetApiV1ResultsReturnOrdersData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Batch Request Id
         */
        batch_request_id: string;
    };
    url: '/api/v1/results/return-orders';
};

export type GetApiV1ResultsReturnOrdersErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    /**
     * Not Found
     */
    404: BadRequestSchema;
    default: unknown;
};

export type GetApiV1ResultsReturnOrdersError = GetApiV1ResultsReturnOrdersErrors[keyof GetApiV1ResultsReturnOrdersErrors];

export type GetApiV1ResultsReturnOrdersResponses = {
    /**
     * OK
     */
    200: ReturnResultsSchema;
};

export type GetApiV1ResultsReturnOrdersResponse = GetApiV1ResultsReturnOrdersResponses[keyof GetApiV1ResultsReturnOrdersResponses];

export type GetApiV1ResultsShipOrdersData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Batch Request Id
         */
        batch_request_id: string;
    };
    url: '/api/v1/results/ship-orders';
};

export type GetApiV1ResultsShipOrdersErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    /**
     * Not Found
     */
    404: BadRequestSchema;
    default: unknown;
};

export type GetApiV1ResultsShipOrdersError = GetApiV1ResultsShipOrdersErrors[keyof GetApiV1ResultsShipOrdersErrors];

export type GetApiV1ResultsShipOrdersResponses = {
    /**
     * OK
     */
    200: ShipmentOrderResultsResponseSchema;
};

export type GetApiV1ResultsShipOrdersResponse = GetApiV1ResultsShipOrdersResponses[keyof GetApiV1ResultsShipOrdersResponses];

export type GetApiV1OrdersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Order number
         * Order number to search for.
         */
        order_number?: string | null;
        /**
         * Customer key
         * Customer key to search for.
         */
        customer_key?: string | null;
        /**
         * Carrier Key
         * Carrier of the order to filter by. Choose from: "DHL_STD_NATIONAL", "HERMES_KLV", "HERMES_STD_NATIONAL", "DHL_AT", "DHL_POST_AUT", "HERMES_POST_AUT", "POST_CH", "QUICK_CH", "POST_NL", "DHL_NL", "DHL_PL", "DPD_PL", "UB_POST_PL", "PPL", "ZASIL_CZ", "BPOST_BE", "DHL_BPOST_BEL", "COLI_FR", "UB_GLS_DK", "UB_CORR_ES", "DS_TB_ES", "UB_SEUR_ES", "UB_CTT_PT", "DS_TB_PT", "DPD_PT", "ECONT_BG", "ACS_CY", "UB_OMNIVA_EE", "UB_POST_FI", "UB_TAXY_GR", "ACS_GR", "POST_HR", "POST_HU", "GLS_HU", "DPD_HU", "UB_FAST_IE", "POST_IT", "DS_TB_IT", "UB_OMNIVA_LT", "BPOST_LU", "UB_OMNIVA_LV", "UB_POST_NO", "FAN_RO", "UB_DHL_SE", "POST_SI", "POST_SK", "ZASIL_SK".
         */
        carrier_key?: Carrier | null;
        /**
         * Shop country
         * Shop country to search for.
         */
        shop_country?: string | null;
        /**
         * Status
         * Status of the order to filter by. Choose from: "open", "shipped", "cancelled", "returned", "mixed".
         */
        order_status?: OrdersAppModelsOrderOrderStatusChoices | null;
        /**
         * Status of the order item to filter by. Choose from: "open", "shipped", "cancelled", "returned".
         */
        order_item_status?: OrdersAppModelsOrderItemOrderItemStatusChoices | null;
        /**
         * Orders from
         * Orders from date to filter by.
         */
        orders_from?: string | null;
        /**
         * Orders to
         * Orders to date to filter by.
         */
        orders_to?: string | null;
        /**
         * Fulfillment type
         * Fulfillment type to filter by.
         */
        fulfillment_type?: FulfillmentTypes | null;
        /**
         * Page
         * Page number to retrieve items from.
         */
        page?: number;
        /**
         * Per Page
         * Number of items per page.
         */
        per_page?: number;
    };
    url: '/api/v1/orders/';
};

export type GetApiV1OrdersErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    default: unknown;
};

export type GetApiV1OrdersError = GetApiV1OrdersErrors[keyof GetApiV1OrdersErrors];

export type GetApiV1OrdersResponses = {
    /**
     * OK
     */
    200: PagedGetOrderSchema;
};

export type GetApiV1OrdersResponse = GetApiV1OrdersResponses[keyof GetApiV1OrdersResponses];

export type GetApiV1OrdersByOrderNumberDeliveryDocumentData = {
    body?: never;
    path: {
        /**
         * Order Number
         */
        order_number: string;
    };
    query?: never;
    url: '/api/v1/orders/{order_number}/delivery_document';
};

export type GetApiV1OrdersByOrderNumberDeliveryDocumentErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    /**
     * Internal Server Error
     */
    500: BadRequestSchema;
    default: unknown;
};

export type GetApiV1OrdersByOrderNumberDeliveryDocumentError = GetApiV1OrdersByOrderNumberDeliveryDocumentErrors[keyof GetApiV1OrdersByOrderNumberDeliveryDocumentErrors];

export type GetApiV1OrdersByOrderNumberDeliveryDocumentResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type GetApiV1OrdersByOrderNumberDeliveryDocumentResponse = GetApiV1OrdersByOrderNumberDeliveryDocumentResponses[keyof GetApiV1OrdersByOrderNumberDeliveryDocumentResponses];

export type GetApiV1OrdersByOrderNumberInvoiceData = {
    body?: never;
    path: {
        /**
         * Order Number
         */
        order_number: string;
    };
    query?: never;
    url: '/api/v1/orders/{order_number}/invoice';
};

export type GetApiV1OrdersByOrderNumberInvoiceErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    /**
     * Internal Server Error
     */
    500: BadRequestSchema;
    default: unknown;
};

export type GetApiV1OrdersByOrderNumberInvoiceError = GetApiV1OrdersByOrderNumberInvoiceErrors[keyof GetApiV1OrdersByOrderNumberInvoiceErrors];

export type GetApiV1OrdersByOrderNumberInvoiceResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type GetApiV1OrdersByOrderNumberInvoiceResponse = GetApiV1OrdersByOrderNumberInvoiceResponses[keyof GetApiV1OrdersByOrderNumberInvoiceResponses];

export type PostApiV1OrdersCancelData = {
    body: CancelRequestSchema;
    path?: never;
    query?: never;
    url: '/api/v1/orders/cancel';
};

export type PostApiV1OrdersCancelErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    default: unknown;
};

export type PostApiV1OrdersCancelError = PostApiV1OrdersCancelErrors[keyof PostApiV1OrdersCancelErrors];

export type PostApiV1OrdersCancelResponses = {
    /**
     * OK
     */
    200: BatchRequestResponseSchema;
};

export type PostApiV1OrdersCancelResponse = PostApiV1OrdersCancelResponses[keyof PostApiV1OrdersCancelResponses];

export type PostApiV1OrdersShipData = {
    body: ShipmentRequestSchema;
    path?: never;
    query?: never;
    url: '/api/v1/orders/ship';
};

export type PostApiV1OrdersShipErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    default: unknown;
};

export type PostApiV1OrdersShipError = PostApiV1OrdersShipErrors[keyof PostApiV1OrdersShipErrors];

export type PostApiV1OrdersShipResponses = {
    /**
     * OK
     */
    200: BatchRequestResponseSchema;
};

export type PostApiV1OrdersShipResponse = PostApiV1OrdersShipResponses[keyof PostApiV1OrdersShipResponses];

export type PostApiV1OrdersReturnData = {
    body: ReturnRequestSchema;
    path?: never;
    query?: never;
    url: '/api/v1/orders/return';
};

export type PostApiV1OrdersReturnErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    default: unknown;
};

export type PostApiV1OrdersReturnError = PostApiV1OrdersReturnErrors[keyof PostApiV1OrdersReturnErrors];

export type PostApiV1OrdersReturnResponses = {
    /**
     * OK
     */
    200: BatchRequestResponseSchema;
};

export type PostApiV1OrdersReturnResponse = PostApiV1OrdersReturnResponses[keyof PostApiV1OrdersReturnResponses];

export type GetApiV1ReportsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Report type
         * Filter by report type. Choose from: "SELLABLE_STOCK", "WAREHOUSE_MOVEMENTS".
         */
        type?: ReportType | null;
        /**
         * Search query
         * Search query to filter reports by ID.
         */
        query?: string | null;
        /**
         * Page
         * Page number to retrieve items from.
         */
        page?: number;
        /**
         * Per Page
         * Number of items per page.
         */
        per_page?: number;
    };
    url: '/api/v1/reports/';
};

export type GetApiV1ReportsErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    default: unknown;
};

export type GetApiV1ReportsError = GetApiV1ReportsErrors[keyof GetApiV1ReportsErrors];

export type GetApiV1ReportsResponses = {
    /**
     * OK
     */
    200: PagedReportSchema;
};

export type GetApiV1ReportsResponse = GetApiV1ReportsResponses[keyof GetApiV1ReportsResponses];

export type GetApiV1ReportsByReportIdDownloadData = {
    body?: never;
    path: {
        /**
         * Report Id
         */
        report_id: number;
    };
    query?: never;
    url: '/api/v1/reports/{report_id}/download';
};

export type GetApiV1ReportsByReportIdDownloadErrors = {
    /**
     * Bad Request
     */
    400: BadRequestSchema;
    /**
     * Unauthorized
     */
    401: BadRequestSchema;
    /**
     * Forbidden
     */
    403: BadRequestSchema;
    /**
     * Not Found
     */
    404: BadRequestSchema;
    /**
     * Internal Server Error
     */
    500: BadRequestSchema;
};

export type GetApiV1ReportsByReportIdDownloadError = GetApiV1ReportsByReportIdDownloadErrors[keyof GetApiV1ReportsByReportIdDownloadErrors];

export type GetApiV1ReportsByReportIdDownloadResponses = {
    default: unknown;
};

export type ClientOptions = {
    baseURL: string;
};