name: Update API client

on:
  schedule:
    - cron: '0 0 * * *' # daily at midnight UTC
  push:
    branches:
      - main # include main so it triggers here too
  workflow_dispatch:

jobs:
  update-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      - name: Fetch latest OpenAPI spec
        run: curl -L https://partner.aboutyou.com/api/v1/openapi.json -o openapi.json

      - name: Clean operationId fields
        run: 'sed -i ''/"operationId": "scapi_app_endpoints_.*_api_.*",/d'' openapi.json'

      - run: npm run openapi-ts

      - name: Check for changes
        id: git-check
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and tag release
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add openapi.json src
          git commit -m "chore: update OpenAPI client" || true
          npm version patch -m "chore: release %s"
          git push --follow-tags

      - name: Publish to npm
        if: steps.git-check.outputs.changed == 'true' && github.ref == 'refs/heads/main'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public

      - name: Create GitHub Release
        if: steps.git-check.outputs.changed == 'true' && github.ref == 'refs/heads/main'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
